module: py
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /helloworld
  script: helloworld.app    # app variable in helloworld.py
- url: /clock
  script: clock.app         # app variable in clock.py
- url: /clock/prefs
  script: prefs.app
  login: required
  
libraries:
  - name: jinja2
    version: "2.6"
  - name: markupsafe
    version: "0.15"